branch-defaults:
  master:
    environment: Nochntest-env
deploy:
  artifact: dist/Archive.zip
environment-defaults:
  Nochntest-env:
    branch: null
    repository: null
global:
  application_name: nochntest
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
